version: 2.1

orbs:
  node: circleci/node@2.1.0

jobs:
  publish:
    executor:
      name: node/default
      tag: '14.2.0'
    steps:
      - checkout
      - node/install:
          node-version: 14.2.0
      - node/install-packages:
          cache-key: package.json
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  publish-sdk:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - main
